### PR TITLE
feat: add Kong Hybrid mode on GCP

### PR DESCRIPTION
**Pull request by vbelouso**

### CODE REVIEW

**Comment by cmwylie19** [comment]
Unable to move forward from **Portainer checking**, looks like a firewall problem. This is resolvable from within the VM but not outside.

```
➜  ~ curl -v http://34.66.147.103:9000/
*   Trying 34.66.147.103:9000...
* connect to 34.66.147.103 port 9000 failed: Operation timed out
* Failed to connect to 34.66.147.103 port 9000 after 75011 ms: Operation timed out
* Closing connection 0
curl: (28) Failed to connect to 34.66.147.103 port 9000 after 75011 ms: Operation timed out
```

**Comment by cmwylie19** [comment]
I noticed in the VM console that the firewall is disabled.
image


The doc says to have those open.
image

**Comment by cmwylie19** [comment]
**Configure Kong Konnect Enterprise Chart** section

You copy the helm values file to `konnect-dp.yaml`. Then later we apply a helm overrides file with `oc apply`? This does not work. This should be an instance of the `Kong` operator. 

This section needs a `Kong Operator` instance to apply, preferably one that uses $KONG_CP_URL that can be referenced by environmental variable.

**Comment by cmwylie19** [comment]
In **Kong Konnect Enterprise Control Plane**, we are creating an instance of a VM in google.  Due to the fact that we are all using the same project in GCP, if more than one person is testing this document they would have to creat a new `GCP_VM_NAME`. It is extremely simple to miss the hard coded `--tags` sections in the `gcloud compute instances create` command. This stopped me from being able to proceed the first time i ran it.

It would be simple if the tags command were referencing `$GCP_VM_NAME` like the command references `$GCP_PROJECT_NAME` and `$GCP_ZONE`. Change the hardcoded tags to `--tags=$GCP_VM_NAME`

**Comment by vbelouso** [comment]
> This information was not in Claudio's doc. We could save a lot of time and effort by stating which OCP version to use.
> 
> Maybe it was already in there and I missed it somewhere?

No, you didn't miss anything. The original version of the document mentioned the use of OCP 4.7. I tested on 4.8. As you correctly mentioned, we need to explicitly mention which versions we tested.
I will fix this

**Comment by vbelouso** [comment]
> It would be simple if the tags command were referencing `$GCP_VM_NAME` like the command references `$GCP_PROJECT_NAME` and `$GCP_ZONE`. Change the hardcoded tags to `--tags=$GCP_VM_NAME`

You're right about the tags. But I was treating the document as being provided to Customers. In this case, they should not (?) have several virtual machines with Control Plane. Accordingly, the issue with the firewall will be irrelevant.

If we want to make this process as flexible as possible for _our testing_, then I have one more suggestion. I think you encountered this when creating firewall rules. GCP does not allow to create firewall rules with the same name. Perhaps we should use the VM name as a prefix/postfix. But in general, I don’t really like this idea, it seems to me more suitable for testing

**Comment by cmwylie19** [comment]
> 

Very good thoughts, i personally really like that idea for our testing since it would allow someone that was unfamiliar with the inner workings of GCP to get through easily. At the end of the day i don't see this as a "big deal" because more than likely there will not be more than one person testing at a time. I definitely do see your point. This is great work, and a really long doc. Just pointing this out incase we get in a position where multiple people are testing at the same time.

**Comment by vbelouso** [comment]
> I kept hitting this error while trying to install the Operator. It happened on OCP 4.10 and 4.9. "apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; "
> 
> Turns out that the cluster must be an OCP Cluster <= v4.8 as 4.8 uses Kubernetes 1.21.

Fixed, I mentioned testing versions with reference document about changes in CRD

> It would be simple if the tags command were referencing `$GCP_VM_NAME` like the command references `$GCP_PROJECT_NAME` and `$GCP_ZONE`. Change the hardcoded tags to `--tags=$GCP_VM_NAME`

Fixed, replaced tags with `GCP_VM_NAME` and firewall rules like `rule-name-GCP_VM_NAME` to support our testing purpose.


> You copy the helm values file to `konnect-dp.yaml`. Then later we apply a helm overrides file with `oc apply`? This does not work. This should be an instance of the `Kong` operator.

Totally correct. Rewrited this section

**Review by JudeNiroshan — CHANGES_REQUESTED** [review]

**Comment by mpaulgreen** [comment]
This is not required at this point. The task was for mesh.

**Pull request closed without merging**
